# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactiv', '0003_auto_20170803_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivlocation',
            name='categorie',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
