# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactiv', '0004_interactivlocation_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
