# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactiv', '0005_interactivlocation_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
