# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactiv', '0006_auto_20170803_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactivlocation',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
