# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactiv', '0007_auto_20170803_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactivlocation',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
